logging:
  mode: offline
  project: UNIonConicx40Linear
  notes: UNIonConicx40Linear
  log_comment: UNIAdapteronConicx40LinearPatientOptOverlap
  tags:
  - tag1
  - tag2
  - '...'
  wandb_dir: /xxx/CellVTA/logs
  log_dir: /xxx/CellVTA/logs/2025-02-19T193050_UNIAdapteronConicx40LinearPatientOptOverlap
  level: info
  log_images: null
  group: null
  run_id: ukp1t3m7
  wandb_file: ukp1t3m7
random_seed: 19
gpu: 0
data:
  dataset: Conic
  dataset_path: /xxx/conic_cellvit_patient_x40_linear_withOverlap
  train_folds:
  - 0
  val_split: 0.2
  test_folds:
  - 1
  num_nuclei_classes: 7
  num_tissue_classes: 1
  input_shape: 256
model:
  backbone: UNI_Adapter
  pretrained_encoder: /xxx/UNI/pretrained_models/vit_large_patch16_224.dinov2.uni_mass100k/pytorch_model.bin
  pretrained: null
  embed_dim: 1024
  input_channels: null
  depth: 24
  num_heads: 16
  extract_layers: null
  shared_decoders: null
  regression_loss: null
loss:
  nuclei_binary_map:
    focaltverskyloss:
      loss_fn: FocalTverskyLoss
      weight: 1
    dice:
      loss_fn: dice_loss
      weight: 1
  hv_map:
    mse:
      loss_fn: mse_loss_maps
      weight: 2.5
    msge:
      loss_fn: msge_loss_maps
      weight: 8
  nuclei_type_map:
    bce:
      loss_fn: xentropy_loss
      weight: 0.5
    dice:
      loss_fn: dice_loss
      weight: 0.2
    mcfocaltverskyloss:
      loss_fn: MCFocalTverskyLoss
      weight: 0.5
      args:
        num_classes: 7
  tissue_types:
    ce:
      loss_fn: CrossEntropyLoss
      weight: 0.1
training:
  drop_rate: 0
  attn_drop_rate: 0.1
  drop_path_rate: 0.1
  batch_size: 8
  epochs: 50
  optimizer: AdamW
  early_stopping_patience: 50
  scheduler:
    scheduler_type: exponential
    hyperparameters:
      gamma: 0.85
  optimizer_hyperparameter:
    betas:
    - 0.85
    - 0.95
    lr: 0.0003
    weight_decay: 0.0001
  unfreeze_epoch: 51
  eval_every: 5
transformations:
  randomrotate90:
    p: 0.2
  horizontalflip:
    p: 0.2
  verticalflip:
    p: 0.2
  blur:
    p: 0.2
    blur_limit: 10
  gaussnoise:
    p: 0.5
    var_limit: 10
  colorjitter:
    p: 0.2
    scale_setting: 0.25
    scale_color: 0.1
  superpixels:
    p: 0.1
  zoomblur:
    p: 0.1
  randomsizedcrop:
    p: 0.2
  elastictransform:
    p: 0.2
  normalize:
    mean:
    - 0.5
    - 0.5
    - 0.5
    std:
    - 0.5
    - 0.5
    - 0.5
eval_checkpoint: model_best.pth
run_sweep: false
agent: null
dataset_config:
  tissue_types:
    Colon: 0
  nuclei_types:
    background: 0
    neutrophil: 1
    epithelial: 2
    lymphocyte: 3
    plasma: 4
    eosinophil: 5
    connective: 6
