logging:
  mode: offline
  project: UNIonPannuke
  notes: UNIonPannuke
  log_comment: UNIAdapteronPannukeOptCfgSplit3
  tags:
  - tag1
  - tag2
  - '...'
  wandb_dir: /xxx/CellVTA/logs
  log_dir: /xxx/CellVTA/logs/2025-01-29T021004_UNIAdapteronPannukeOptCfgSplit3
  level: info
  log_images: null
  group: null
  run_id: nmgyykmj
  wandb_file: nmgyykmj
random_seed: 19
gpu: 0
data:
  dataset: Pannuke
  dataset_path: /xxx/pannuke_cellvit
  train_folds:
  - 2
  val_folds:
  - 1
  test_folds:
  - 0
  num_nuclei_classes: 6
  num_tissue_classes: 19
  input_shape: 256
model:
  backbone: UNI_Adapter
  pretrained_encoder: /xxx/UNI/pretrained_models/vit_large_patch16_224.dinov2.uni_mass100k/pytorch_model.bin
  pretrained: null
  embed_dim: 1024
  input_channels: null
  depth: 24
  num_heads: 16
  extract_layers: null
  shared_decoders: null
  regression_loss: null
loss:
  nuclei_binary_map:
    focaltverskyloss:
      loss_fn: FocalTverskyLoss
      weight: 1
    dice:
      loss_fn: dice_loss
      weight: 1
  hv_map:
    mse:
      loss_fn: mse_loss_maps
      weight: 2.5
    msge:
      loss_fn: msge_loss_maps
      weight: 8
  nuclei_type_map:
    bce:
      loss_fn: xentropy_loss
      weight: 0.5
    dice:
      loss_fn: dice_loss
      weight: 0.2
    mcfocaltverskyloss:
      loss_fn: MCFocalTverskyLoss
      weight: 0.5
      args:
        num_classes: 6
  tissue_types:
    ce:
      loss_fn: CrossEntropyLoss
      weight: 0.1
training:
  drop_rate: 0
  attn_drop_rate: 0.1
  drop_path_rate: 0.1
  batch_size: 8
  epochs: 100
  optimizer: AdamW
  early_stopping_patience: 100
  scheduler:
    scheduler_type: exponential
    hyperparameters:
      gamma: 0.85
  optimizer_hyperparameter:
    betas:
    - 0.85
    - 0.95
    lr: 0.0003
    weight_decay: 0.0001
  unfreeze_epoch: 101
  sampling_gamma: 0.85
  sampling_strategy: cell+tissue
transformations:
  randomrotate90:
    p: 0.2
  horizontalflip:
    p: 0.2
  verticalflip:
    p: 0.2
  blur:
    p: 0.2
    blur_limit: 10
  gaussnoise:
    p: 0.5
    var_limit: 10
  colorjitter:
    p: 0.2
    scale_setting: 0.25
    scale_color: 0.1
  superpixels:
    p: 0.1
  zoomblur:
    p: 0.1
  randomsizedcrop:
    p: 0.2
  elastictransform:
    p: 0.2
  normalize:
    mean:
    - 0.5
    - 0.5
    - 0.5
    std:
    - 0.5
    - 0.5
    - 0.5
eval_checkpoint: model_best.pth
run_sweep: false
agent: null
dataset_config:
  tissue_types:
    Adrenal_gland: 0
    Bile-duct: 1
    Bladder: 2
    Breast: 3
    Cervix: 4
    Colon: 5
    Esophagus: 6
    HeadNeck: 7
    Kidney: 8
    Liver: 9
    Lung: 10
    Ovarian: 11
    Pancreatic: 12
    Prostate: 13
    Skin: 14
    Stomach: 15
    Testis: 16
    Thyroid: 17
    Uterus: 18
  nuclei_types:
    Background: 0
    Neoplastic: 1
    Inflammatory: 2
    Connective: 3
    Dead: 4
    Epithelial: 5
